### ISSUE TITLE
must clarify protocol used in README.md

### ISSUE THREAD

**Issue by nahuel** [tonsky/net.async#1]
I come to net.async thinking it was a generic tcp-connection handler library, but it uses a custom protocol (so for example you cannot really implement SMTP using it). I discovered this after reading the source, I think it must be stated in the README.md.

**Comment by tonsky** [comment]
Agree, feel free to correct via pull request.

**Comment by GutZuFusss** [comment]
@tonsky I would be happy to make a PR, if you could just point out the differences to plain TCP for me? At first glance I only noticed the read/write-bufs to be a little unusual.

**Comment by tonsky** [comment]
Updated
